# Audit Event Types Constants
IMPORT_STARTED = "IMPORT_STARTED"
IMPORT_COMPLETED = "IMPORT_COMPLETED"
IMPORT_FAILED = "IMPORT_FAILED"
STAGING_MODIFIED = "STAGING_MODIFIED"
PROMOTION_STARTED = "PROMOTION_STARTED"
PROMOTION_COMPLETED = "PROMOTION_COMPLETED"
